
# Specify what the robot base is and what the world base is
world_base: odom
robot_base: body

# TODO
num_cameras: 1
update_policy: fifo
# Configurable section
cameras_registered:
  realsense:
    image_rectified: /camera/color/image_raw
    depth_registered: /camera/depth/image_raw
    camera_info: /camera/depth/camera_info
    # By not specifying these, we lookup the transform frame instead. (They do no need to be specified)
    pose_with_covariance: ''
    pose: ''
# TODO: make the below work
#cameras_raw:

# Define intermediate joints needed, but id them with
# child link to keep uniqueness.
joints: ''
