semseg:
  package: pytorch_encoding_wrapper
  model: EncNet_ResNet50s_ADE
  extra_args: []
  num_labels: 150
  ongpu_projection: True
  # The following is only useful for when there are many labels, like 120+
  # It should be benchmarked on a per-system basis
  onehot_projection: True
